baseURL = 'https://kamocast.forrexlapis.win/'
languageCode = 'ja-JP'
title = 'kamocast'
theme = "podcast-theme"

[params]
podcastImage = "images/test.webp"
author = "かもしか"
email = "nirai2815@gmail.com"